[ADD] :rocket: --> Added configuration file for commit type + git command (add or delete) + Removed glib assertion issue

diff --git a/gitsc b/gitsc
--- a/gitsc
+++ b/gitsc
@@ -1,47 +1,66 @@
 #!/bin/bash
-#Types of commit message
-commit+=("[ADD]" "[MODIFY]" "[COD.STY]" "[FIX]" "[HANDLE]" "[INCLUDE]" "[LIB]" "[REMOVE]" "[UNIT.TESTS]" "[MERGE]" "CommitNorm")
-# info_commit+=("Adding a new feature" "Modifying a functionnality" "Fixing the coding style" "Fixing a feature" \
-#  "Handling a new feature" "Including new things in the header" "Modifying a library", "Removing a functionnality", "Adding tests to your code")
-#Get modified files
+gitcmd=add
+# Parsing commit types
+INPUT=gitsc.conf
+OLDIFS=$IFS
+IFS=','
+[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 22; }
+while read line emoji status; do
+    commit+=( "$line" )
+    gitmoji+=( "$emoji" )
+    status_type+=( "$status" )
+done < $INPUT
+IFS=$OLDIFS
+
+# Get modified files
 mod=($({ git diff --name-only ; git diff --name-only --staged ; } | sort | uniq))
-#Get untracked files
+
+# Get untracked files
 unt=($(git ls-files --other --exclude-standard))
-#Get all files
+
+# Get all files
 all_files=($(git ls-files))
-if [ "$#" = 1 ] && [ "$1" = "." ]; then
-  echo "Usage: gitsc ."
+if [ $? != 0 ]; then
+  clear
+  echo "Not a git repository"
+  exit
 fi
-#Pre-processing
+if [ "$#" = 1 ] && [ "$1" != "." ]; then
+  echo "Usage: gitsc or gitsc ."
+  exit 1
+fi
+
+# Pre-processing
 for (( i=0; i<${#mod[@]}; ++i)); do
     data+=( "${mod[$i]}" )
 done
 for (( i=0; i<${#unt[@]}; ++i)); do
     data+=( "${unt[$i]}" )
 done
+if (( ${#commit[@]} % 2 == 0 )) ; then
+  commit+=( "GitShortcuts" )
+fi
 if (( ${#data[@]} % 2 == 0 )) ; then
-  data+=( "This file can't be added your current repository" )
+  data+=( "This file can't be added to your repository" )
 fi
 if (( ${#all_files[@]} % 2 == 0 )) ; then
-  all_files+=( "This file can't be added your current repository" )
+  all_files+=( "This file can't be added to your repository" )
 fi
-#Commit type interface
-commitchose=$(zenity --list --window-icon=GitShortcut.png --title='Git Shortcuts' --text="Choose commit type" \
+
+# Commit type interface
+commitchose=$(zenity --list --title='Git Shortcuts' --text="Choose commit type" \
 --width=600 --height=350 --column='Choose your' "${commit[@]}" --radiolist --column=' commit type' "${commit[@]}" )
 if [ $? != 0 ] ; then
   exit
 fi
 
-#File interface
+# File interface
 if [ "$#" != 1 ] ; then
-  if [ $commitchose = "CommitNorm" ] ; then
-    zenity --error --width=200 --height=100 --text="You must choose a commit type"
-    exit
-  elif [ $commitchose != "[REMOVE]" ] ; then
-    filechose=$(zenity --list --window-icon=GitShortcut.png --separator=" " --title='Git Shortcuts' --text="Choose file(s) to add" \
+  if [ "$commitchose" != [REMOVE] ] && [ "$commitchose" != "GitShortcuts" ]; then
+    filechose=$(zenity --list --separator=" " --title='Git Shortcuts' --text="Choose file(s) to add" \
     --width=600 --height=600  --checklist --column='Add' "${data[@]}"  --column='File name' "${data[@]}")
-  elif [ $commitchose = "[REMOVE]" ] ; then
-    filechose=$(zenity --list --window-icon=GitShortcut.png --separator=" " --title='Git Shortcuts' --text="Choose file(s) to remove" \
+  elif [ "$commitchose" = [REMOVE] ]  && [ "$commitchose" != "GitShortcuts" ]; then
+    filechose=$(zenity --list --separator=" " --title='Git Shortcuts' --text="Choose file(s) to remove" \
     --width=600 --height=600  --checklist --column='Add' "${all_files[@]}"  --column='File name' "${all_files[@]}")
   else
     zenity --error --width=200 --height=100 --text="You must specify a commit type"
@@ -52,63 +71,40 @@ if [ $? != 0 ] ; then
   exit
 fi
 
-#Commit message interface
-ask=$(zenity --entry --window-icon=GitShortcut.png --title='Git Shortcuts' --text="Type your commit message" \
+# Commit message interface
+ask=$(zenity --entry --title='Git Shortcuts' --text="Type your commit message" \
 --width=600 --height=120)
 if [ $? != 0 ] ; then
   zenity --warning --title='Git Shortcuts' --text="File(s) not added" --width=150 --height=120
   exit
 fi
 
-# Git add .
+# Choose add/remove command
+for (( i=0; i<${#commit[@]}; ++i)); do
+  if [ "${commit[$i]}" = "$commitchose" ] ; then
+  gitcmd="${status_type[$i]}"
+  fi
+done
+
+# Git add/rm .
 if [ "$#" = 1 ] && [ "$1" = "." ]; then
-  if [ $commitchose != [REMOVE] ] ; then
-    git add .
-  elif [ $commitchose = [REMOVE] ] ; then
-    git rm .
-  else
-    exit
-  fi
+    git $gitcmd .
 else
-  # Git add command
-  if [ $commitchose != [REMOVE] ] ; then
-    for (( i=0; i<${#filechose[@]}; ++i)); do
-      git add ${filechose[i]}
-    done
-  elif [ $commitchose = [REMOVE] ] ; then
-    for (( i=0; i<${#filechose[@]}; ++i)); do
-      git rm ${filechose[i]}
-    done
-  else
-    exit
-  fi
+  # Git add/rm command
+  for (( i=0; i<${#filechose[@]}; ++i)); do
+    git $gitcmd ${filechose[i]}
+  done
 fi
 
-#Commit message selection
-if [ "$commitchose" = "[ADD]" ]; then
-    git commit -m "[ADD] :rocket: --> $ask"
-elif [ "$commitchose" = "[MODIFY]" ]; then
-    git commit -m "[MODIFY] :sparkles: --> $ask"
-elif [ "$commitchose" = "[COD.STY]" ]; then
-    git commit -m "[COD.STY] :zap: --> $ask"
-elif [ "$commitchose" = "[FIX]" ]; then
-    git commit -m "[FIX] :bug: --> $ask"
-elif [ "$commitchose" = "[HANDLE]" ]; then
-    git commit -m "[HANDLE] :sparkles: --> $ask"
-elif [ "$commitchose" = "[INCLUDE]" ]; then
-    git commit -m "[INCLUDE] :wrench: --> $ask"
-elif [ "$commitchose" = "[LIB]" ]; then
-    git commit -m "[LIB] :wrench: --> $ask"
-elif [ "$commitchose" = "[REMOVE]" ]; then
-    git commit -m "[REMOVE] :fire: --> $ask"
-elif [ "$commitchose" = "[UNIT.TESTS]" ]; then
-    git commit -m "[UNIT.TESTS] :white_check_mark: --> $ask"
-elif [ "$commitchose" = "[MERGE]" ]; then
-    git commit -m "[MERGE] :twisted_rightwards_arrows: --> $ask"
-else
-  exit
-fi
-push=$(zenity --question --window-icon=GitShortcut.png --title='Git Shortcuts' --text="Do you want to push" \
+# Commit message selection
+for (( i=0; i<${#commit[@]}; ++i)); do
+  if [ "${commit[$i]}" = "$commitchose" ] ; then
+   git commit -m "${commit[$i]} ${gitmoji[$i]} --> $ask"
+  fi
+done
+
+# Git push
+push=$(zenity --question --title='Git Shortcuts' --text="Do you want to push" \
 --width=300 --height=120)
 if [ $? != 0 ] ; then
   exit
