[FIX] :bug: --> Fixed auto-update + Exit status

diff --git a/gitsc b/gitsc
--- a/gitsc
+++ b/gitsc
@@ -1,5 +1,6 @@
 #!/bin/bash
 check_version() {
+  cd $HOME/Git-Shortcuts
   last_ref=$(git rev-parse --short origin/main)
   cur_ref=$(git rev-parse --short HEAD)
   if [ "$cur_ref" != "$last_ref" ]; then
@@ -10,6 +11,7 @@ check_version() {
             * ) echo "Update not installed";;
     esac
   fi
+  cd - &> /dev/null
 }
 
 parsing_configuration_file() {
@@ -61,25 +63,6 @@ fill_arrays() {
   fi
   if (( ${#all_files[@]} % 2 == 0 )) ; then
     all_files+=( "This file can't be added to your repository" )
-  fi
-}
-
-gitsc_options() {
-  if [ "$#" = 1 ] && [ "$1" = "--log" ]; then
-    git shortlog > gitlog.txt
-    enscript -p gitlog.ps gitlog.txt
-    ps2pdf gitlog.ps gitlog.pdf
-    rm *gitlog.txt* *gitlog.ps*
-    echo "gitsc: Successfuly generated PDF file."
-    exit 0
-  fi
-  if [ "$#" = 1 ] && [ "$1" = "--help" ]; then
-    man gitsc
-    exit 0
-  fi
-  if [ "$#" = 1 ] && [ "$1" != "." ] && [ "$1" != "--all" ]; then
-    echo "gitsc: Invalid option. Try gitsc --help for more informations"
-    exit 1
   fi
 }
 
@@ -168,11 +151,26 @@ git_interaction() {
 }
 
 check_version
+if [ "$#" = 1 ] && [ "$1" = "--log" ]; then
+  git shortlog > gitlog.txt
+  enscript -p gitlog.ps gitlog.txt
+  ps2pdf gitlog.ps gitlog.pdf
+  rm *gitlog.txt* *gitlog.ps*
+  echo "gitsc: Successfuly generated PDF file."
+  exit 0
+fi
+if [ "$#" = 1 ] && [ "$1" = "--help" ]; then
+  man gitsc
+  exit 0
+fi
+if [ "$#" = 1 ] && [ "$1" != "." ] && [ "$1" != "--all" ]; then
+  echo "gitsc: Invalid option. Try gitsc --help for more informations"
+  exit 1
+fi
 parsing_configuration_file
 get_files
 fill_arrays
 check_repository
-gitsc_options
 choose_commit
 choose_file
 type_message
